using System.Runtime.CompilerServices;

namespace ArcPyNet;

public class _3DAnalyst
{
    internal _3DAnalyst() { }
}

public static class _3DAnalystExt
{
    private static Code Run(object?[] args, [CallerMemberName] string method = "")
    {
        return ArcPy.Instance.Run($"arcpy.ddd.{method}", args);
    }

    public static Code ASCII3DToFeatureClass(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code AddFeatureClassToTerrain(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code AddSurfaceInformation(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code AddTerrainPoints(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code AddTerrainPyramidLevel(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code AddZInformation(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code AppendTerrainPoints(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Aspect(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Buffer3D(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code BuildTerrain(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ChangeLasClassCodes(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ChangeTerrainReferenceScale(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ChangeTerrainResolutionBounds(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ClassifyLasBuilding(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ClassifyLasByHeight(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ClassifyLasGround(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ClassifyLasNoise(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ClassifyLasOverlap(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ClassifyPointCloudUsingTrainedModel(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ColorizeLas(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ConstructSightLines(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Contour(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ContourList(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ContourWithBarriers(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code CopyTin(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code CreateTerrain(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code CreateTin(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Curvature(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code CutFill(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code DecimateTinNodes(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code DeleteTerrainPoints(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code DelineateTinDataArea(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Difference3D(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Divide(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code EditTin(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code EncloseMultiPatch(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code EnforceRiverMonotonicity(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code EvaluatePointCloudClassificationModel(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ExtractLas(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ExtractMultipatchFromMesh(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ExtractPowerLinesFromPointCloud(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ExtrudeBetween(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code FeatureClassZToASCII(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code FeatureTo3DByAttribute(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code FeaturesFromCityEngineRules(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code FenceDiagram(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Float(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code GenerateClearanceSurface(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code HillShade(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Idw(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Import3DFiles(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Inside3D(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Int(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code InterpolatePolyToPatch(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code InterpolateShape(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Intersect3D(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Intersect3DLineWithMultiPatch(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Intersect3DLineWithSurface(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Intersect3DLines(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Intervisibility(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code IsClosed3D(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Kriging(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code LASToMultipoint(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code LandXMLToTin(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code LasBuildingMultipatch(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code LasDatasetToTin(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code LasHeightMetrics(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code LasPointStatsByArea(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Layer3DToFeatureClass(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code LayerToKML(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code LineOfSight(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code LocateLasPointsByProximity(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code LocateOutliers(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Lookup(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code MapToKML(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code MinimumBoundingVolume(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Minus(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code MultiPatchFootprint(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code NaturalNeighbor(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Near3D(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ObserverPoints(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Plus(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code PointFileInformation(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code PolygonVolume(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code PreparePointCloudTrainingData(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code RasterDomain(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code RasterTin(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code RasterToMultipoint(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ReclassByASCIIFile(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ReclassByTable(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Reclassify(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code RegularizeAdjacentBuildingFootprint(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code RegularizeBuildingFootprint(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code RemoveFeatureClassFromTerrain(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code RemoveTerrainPoints(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code RemoveTerrainPyramidLevel(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ReplaceTerrainPoints(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SetLasClassCodesUsingFeatures(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SetLasClassCodesUsingRaster(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Simplify3DLine(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Skyline(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SkylineBarrier(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SkylineGraph(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Slice(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Slope(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Spline(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SplineWithBarriers(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code StackProfile(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SunShadowFrequency(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SunShadowVolume(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SurfaceAspect(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SurfaceContour(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SurfaceDifference(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SurfaceLength(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SurfaceParameters(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SurfaceSlope(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SurfaceSpot(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code SurfaceVolume(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TerrainToPoints(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TerrainToRaster(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TerrainToTin(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code ThinLas(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TileLas(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Times(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinAspect(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinContour(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinDifference(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinDomain(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinEdge(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinLine(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinNode(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinPolygonTag(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinPolygonVolume(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinRaster(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinSlope(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TinTriangle(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TopoToRaster(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TopoToRasterByFile(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code TrainPointCloudClassificationModel(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Trend(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Union3D(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code UpdateFeatureZ(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Viewshed(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Viewshed2(this _3DAnalyst _, params object?[] args) => Run(args);
    public static Code Visibility(this _3DAnalyst _, params object?[] args) => Run(args);
}
